### ISSUE TITLE
STOP Abusing GitHub Actions 

### ISSUE THREAD

**Issue by reconrex** [Oshekher/AdityaRDP#2]
Please stop abusing GitHub actions. People don't need GUI Interface for educational purposes. This is nonsense. People will only use this to abuse its resources.

**Comment by Oshekher** [comment]
There are many people who really need for educational purposes not all are shit heads who use for inappropriate purposes. Also I have just shared the content which is shared by many people. Even if I make this repo private there are many people who have shared this.
