### ISSUE TITLE
Canceled after few minutes

### ISSUE THREAD

**Issue by freedom-sys3810** [Oshekher/AdityaRDP#3]
I using it then canceled after +- 34 minutes. I using for run kali linux command not to crpyptocurency mining.
Now I canceled after 17 minutes

**Comment by Oshekher** [comment]
No problem you can use it as much as you like just don't do any illegal things that's all.

**Comment by freedom-sys3810** [comment]
I test it now and for future i want to using it for bot whatsapp. 
is this gonna be okay?
